### ISSUE TITLE
Merge shipping, tax, and discounts submodules into core

### ISSUE THREAD

**Issue by jedateach** [burnbright/silverstripe-shop#127]
Development on the discount and shipping modules has progressed well. They are now getting more co-dependent. I thin it is time to commit to these features and combine them into the core shop module.

Currently the issues appear to be arising with the modifiers system.  I'm thinking it might be time to do away with order modifiers: #128

**Comment by wilr** [comment]
Archiving as separate modules was decided the way to go.
