### ISSUE TITLE
Cart abandonment report

### ISSUE THREAD

**Issue by jedateach** [burnbright/silverstripe-shop#145]
Create a report that shows placed vs abandoned orders.

**Comment by markguinn** [comment]
I've got this and another report implemented for another project which I'll be submitting as a PR in the next couple days. 

I've also got 3 dashboard panels for Uncle Cheese's dashboard module (https://github.com/unclecheese/silverstripe-dashboard) - Recent Members, Recent Orders, and Recent Orders as a line graph. @jedateach would you prefer to leave the dashboard stuff in a separate module or include it in core. We could wrap those classes in a `if (class_exists(...))` so they'd only show up if the dashboard module was actually installed.

**Comment by jedateach** [comment]
Excellent @markguinn. I can't imagine another dashboard module being created to replace @unclecheese's module any time soon. Lets add it to core like you suggest, with the `class_exists` wrapper, and also add it to the suggested composer modules.

**Comment by wilr** [comment]
Graph all the things!

**Comment by unclecheese** [comment]
Sweet as!

I could be wrong about this, but in previous conversations I've had about module-specific panels, I've been informed that SilverStripe will not autoload anything that descends from a nonexistent class, so in theory, you should be able to create subclasses of `DashboardPanel` in your module and if the dashboard module doesn't exist, it won't care?

There's always the `module_exists` flag in the Config, but I don't think that helps you here.

**Comment by markguinn** [comment]
Just submitted all of this in PR #303 - I'll leave it open for a few days for comments.

**Comment by markguinn** [comment]
For future reference - Silverstripe can deal with the missing parent class fine as @unclecheese indicated but Code coverage + Scrutinizer bombs out because it tries to look at those classes on their own terms. I did end up using class_exists after all.

**Comment by jedateach** [comment]
We could modify the Travis script to pull in the additional composer
module... Or maybe require-dev might work.

Also note that the coverage tests are split into groups which may need to
be updated.

**Comment by markguinn** [comment]
Once I added class_exists everything passes fine. It's a little ugly but not the end of the word. Would you prefer I add the dashboard module to the travis build?

**Comment by jedateach** [comment]
If everything can be tested together, that definitely helps. We could just do that in the shop demo tests however, so not a biggie.
