### ISSUE TITLE
Issue with 'guest' user and failed payment redirect

### ISSUE THREAD

**Issue by nimeso** [burnbright/silverstripe-shop#230]
If i purchase as a 'guest' and make a decliend payment it redirects me to account/order/123 but because I'm not a member it just gives me a 404 page :(
On a bright note the order does stay in my cart so is there a way if the payment fails to return me to the cart?

**Comment by markguinn** [comment]
I'm not seeing anything left to do on this task. Should we close it or is there something still up for debate?

**Comment by jedateach** [comment]
I'm happy to close it. @nimeso how about you?

**Comment by nimeso** [comment]
Yip :) all seems fine now

On Tue, Jan 27, 2015 at 8:35 AM, Jeremy Shipman <notifications@github.com>
wrote:

> I'm happy to close it. @nimeso <https://github.com/nimeso> how about you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/burnbright/silverstripe-shop/issues/230#issuecomment-71522652>
> .
>



-- 
  q-p
 /\"/\
(`=*=') JAMIE BARKER
 ^---^`-._

   P: +64 3 338 2482
   Skype: jam.dog
