### ISSUE TITLE
Javascript for shop module(s)

### ISSUE THREAD

**Issue by jedateach** [burnbright/silverstripe-shop#232]
Should we create a separate submodule for shop javascript to be maintained in?

I've always held the position that the module shouldn't rely on javascript. That is, [it should at least have fallbacks](https://github.com/burnbright/silverstripe-shop/wiki/Contributing#wiki-good-development-practices) to full page refreshes etc. I also don't want people to be locked into using a particular set of javascript. This is something I like about SilverStripe itself.

However, I know that a javascript laden e-commerce experience will make it much quicker to use. Our lives would be a bit easier if this javascript lived somewhere where we can all contribute to, and collaborate on it.

To get a javascript/ajax rich ui working nicely, we're probably going to need to make some core code changes. I've discussed this a little with @wilr , where we thought a possible solution could be re-writing the `SS_HTTPResponse` objects via decorator callbacks so they contain some json, rather than redirect headers.

I would even be open to someone else heading up this effort, and I can offer any assistance & opinions required.

**Comment by jedateach** [comment]
Thanks for your work on this Mark! Really appreciate the time/effort.
Would you say we can now close this issue?

**Comment by markguinn** [comment]
If you're happy with this solution, I'm happy, Jeremy. I'm still open to merging the shop-ajax module into core though if you'd prefer. This gives users the most flexibility. I'll add shop-ajax as a suggested module.

**Comment by jedateach** [comment]
Can you clarify which approach you think gives the most flexibility? + why

For me, having just the hooks means that I don't need to worry about maintaining any javascript or related server side code.

**Comment by markguinn** [comment]
Sorry for being unclear. It is most flexible to have them in two different modules. This way if someone doesn't like the particular ajax approach I've chosen they can write their own ajax extensions. It sounds like we're on the same page here that leaving them separate is best.
