### ISSUE TITLE
Gateway Method Manual - Needs extension points.

### ISSUE THREAD

**Issue by mediabeastnz** [burnbright/silverstripe-shop#304]
Hi there, I notice that in `OrderProcessor.php` you don't complete the payment if the Gateway is Manual.

I'm wanting to use Manual to process non credit cart payments e.g. account credit but there is no way to get around this line (without hacking):
```if(GatewayInfo::is_manual($gateway)){ // don't complete order }```

Can you put a extend function in there? What do you think?

Happy to do some work on it for you but not sure whats best here.

**Comment by jedateach** [comment]
Hey, I've done some work on handling this in the omnipay module itself.

https://github.com/burnbright/silverstripe-omnipay/commit/1a108313891f887cce877f472c42eea5a846e38a
...which is currently sitting in the 1.2 branch on github.

Basically you can just change some config to make manual payments become "Captured", instead of Authorised.

**Comment by markguinn** [comment]
@mediabeastnz if Jeremy's work on omnipay doesn't help you, I'd suggest subclassing OrderProcessor and using the injector. You can just copy and paste the existing makePayment method into your subclass, change whatever logic you want, and add the following to your yaml config:

```
Injector:
  OrderProcessor:
    class: MyCustomOrderProcessor
```

Assuming you're using 1.0 or dev-master of shop module it uses OrderProcessor::create() everywhere that class is used, which means the injector can just swap in a different class behind the scenes.

**Comment by mediabeastnz** [comment]
Thanks guys both are helpful suggestions.

So have those changes been pushed on to the master branch? I've using the version that the ss-shop gives you which is probably dev-master.

Is this the correct version to use?

**Comment by jedateach** [comment]
I haven't got around to merging it in yet. If you require `1.2.x-dev` in your composer file, I think that should do it. If not, try `1.2.x-dev as dev-master`

**Comment by mediabeastnz** [comment]
Thanks @jedateach
