### ISSUE TITLE
Make AddProductForm more extensible

### ISSUE THREAD

**Issue by jameshoward** [burnbright/silverstripe-shop#312]
If I'm right, SilverStripe’s `Form` class doesn't have a nice way of pushing new fields into an already-constructed instance. You can’t even do `$this->fields->push($newField)` without first calling `setForm` on the new field.

To make it easier to extend `AddProductForm`, it could be refactored to build its fields, actions and validator in separate protected methods `getFields`, `getActions` and `getValidator`. This would allow an overriding class to do as so:

```php
protected function getFields() {
    $fields = parent::getFields();
    $fields->push(new TextField('Test', 'Test'));
    return $fields;
}
```

This would make for cleaner inheritance without the need to copy/paste/edit the `__construct` method.

**Comment by jedateach** [comment]
@jameshoward I'm pretty sure you *can* update the fields of a form that has been instantiated already.

To access Form's fields, call `$form->Fields()`
 Why does form not have `getFields`? I'm not sure.

**Comment by jedateach** [comment]
@jameshoward In all my time working with SilverStripe I've not really had issues setting fields on an already constructed instance, and **not** setting `$field->setForm($form)`. I'm not sure why this is - maybe `setForm` is actually called somewhere else.

But regardless, I think this refactoring tidies things up a bit. I've often put things in the constructor, and assumed that an `Extension` would be used to update the fields. But your approach just opens up even more flexibility.

**Comment by jameshoward** [comment]
@jedateach Yeah, I was doing `$this->fields` from a subclass, which was getting what I expected, a `FieldList`. However, adding fields with `push` caused a non-object error because of https://github.com/silverstripe/silverstripe-framework/blob/3.1/forms/FormField.php#L167

It was trying to get the `Form` related to my added `FormField` and failing. Maybe I'm doing something wrong but I recall having a similar issue previously with a similar attempt to add fields to an existing form rather than building up a field list in the constructor.

**Comment by jedateach** [comment]
I see - thanks for the explanation.
