### ISSUE TITLE
Buyable working example

### ISSUE THREAD

**Issue by mediabeastnz** [burnbright/silverstripe-shop#339]
I've been trying to implement a custom product using the Buyable instruction your docs but obviously I'm missing something?

I have my own custom add to cart for where I'm trying to add my Buyable object to the cart.
    
    public function doSubmit($data, Form $form){
        $cart = ShoppingCart::singleton();
        $cart->add($data, 1);
    }

```$data``` in this instance is the data from the form submission, that didn't work so I had a look to see how the standard Product Page is doing it and noticed there is a getBuyable function that extracts the object...I tried implementing something like this on my custom product controller but ```$this->controller->dataRecord instanceof Buyable``` didn't exist.

Can we get a nice example somewhere?

**Comment by mediabeastnz** [comment]
Ok so after a couple hours of playing around and learning how the cart works a bit better I think i've got it working in the correct way (please let me know if not).

I would still love to see a solid working example rather than referring the test example as per the docs.

Here's my current code from a custom add to cart function:
    $cart = ShoppingCart::singleton();
    
    // get the buyable object to pass into the cart
    $buyable = DataObject::get_by_id('CustomProduct', $data['ProductID']);

    // add custom options to buyable object
    $options = array(
	"FirstName" => $data['FirstName'],
	"LastName" => $data['LastName'],
	"Email" => $data['Email']
    );

    // add the buyable item to the order (if non exists it makes one)
    if($cart->add($buyable, 1, $options)){
        // return to page with success message etc etc.
    }

**Comment by jedateach** [comment]
I'd say look at CustomProductTest for an example. Sorry for lack of docs etc. It has been developed out of need for specific projects. I can't say it has the best implementation, but I've used it in a few different ways now, and it seems to be holding up. Unfortunately it's not as simple as adhering to an interface.

Please do continue to point out any concerns you have, and feel free to implement/propose solutions.

**Comment by mediabeastnz** [comment]
Ok no problem i'll definitely let you know if I make any improvements or have any ideas to suggest.

I'm using it for memberships and events currently e.g. a member can purchase a membership which is a buyable object. It seems to be working well I just need to really understand how the whole buyable class/idea worked.
