### ISSUE TITLE
How to make an product non Editable

### ISSUE THREAD

**Issue by mediabeastnz** [burnbright/silverstripe-shop#350]
I can't find in the docs or code how to make a product non editable.

**Comment by markguinn** [comment]
You want users of the CMS to be unable to make changes to the product, correct? I've never tried to do that but it should be the same as any other Page. It looks to me like you could subclass Product or add an extension to it with a canEdit method that returns false (see SiteTree::canEdit). Does that answer your question at all?

**Comment by mediabeastnz** [comment]
Sorry should of been more descriptive... I see in the templates and on some of the classes that it checks if the product is Editable e.g. in the cart.ss file it hides the quantity field if it's not editable?

**Comment by markguinn** [comment]
Ah. Thanks for the clarification. That reference in Cart.ss is actually not a property of the order or of any product. It's passed into the template to indicate the context (i.e. is this a checkout process or displaying the order after checkout in some way). The two places I can find that use this are:

1. In the main CartPage.ss template, line 13
2. In CartEditField.php, line 71

What's the use case you're hoping to address?

**Comment by mediabeastnz** [comment]
Ahh I see. I've got two products that are custom e.g extend the buyable
object. But they should never be able to be edited in the cart, quantity is
always 1 etc. at the moment I'm just detecting class name but not a
property of the product. Maybe a feature to add?

**Comment by markguinn** [comment]
That sounds like a fine approach. If it's something that comes up frequently we may well add that in but it's also easy enough to handle in the template just like you have. Thanks for bringing this up!
