### ISSUE TITLE
CartEditField breaks when DisplayLogic is installed

### ISSUE THREAD

**Issue by hailwood** [burnbright/silverstripe-shop#356]
In particular it's https://github.com/burnbright/silverstripe-shop/blob/develop/code/cart/CartEditField.php#L66

as most extensions expect the field itself to be passed through, so this breaks as the "ArrayList" does not have the display logic fields it expects.

I expect this isn't just something we will encounter with Display Logic.

**Comment by markguinn** [comment]
That seems like a pretty easy fix. @jedateach you're not using that extension point for anything are you? It looks like a "just in case we need it"

**Comment by jedateach** [comment]
@markguinn - It looks more to me like it has been created to be used somewhere. I'm not sure where though. I usually wrote extension hooks as needed.

**Comment by markguinn** [comment]
I'm not sure what the correct move is here in regards to semantic versioning. This could be regarded as an API breaking change, but we're not even close to release a 2.0 yet. I'm inclined to go ahead and fix this on master and sneak it into 1.2. Any objections?
