### ISSUE TITLE
Display subcategories

### ISSUE THREAD

**Issue by mediaclinic** [burnbright/silverstripe-shop#357]
Is there any documentation, how to display subcategories on front? Default functionality seems to display only one level.

**Comment by markguinn** [comment]
Subcategories are just pages so it really depends on the template. I think the default simple template has recursive navigation so it would show any level of subcategories in the sidebar. Here's another example that would work: https://docs.silverstripe.org/en/3.1/developer_guides/templates/how_tos/navigation_menu/

Is that what you're talking about or are you wanting to display subcategories as part of the product grid or above it on the actual category page?

**Comment by mediaclinic** [comment]
Yes, actually the basic navigation menu were the solution for this case. Thanx for reply.

**Comment by markguinn** [comment]
Happy to help!
