### ISSUE TITLE
Can't fire updateContactDetailsForm() on CheckoutStep_Summary

### ISSUE THREAD

**Issue by mediabeastnz** [burnbright/silverstripe-shop#361]
I can't seem to get my extension to fire Is this extension working correctly?
I see that there is actually to extension hooks named the same inside that class would that cause any issues?

I'm looking to add an extra field e.g. "I declare i'm 18" into that Summary step but having no luck.

**Comment by markguinn** [comment]
I don't think the fact that the hook is called twice should have the effect of fields not showing up at all. I'd suggest adding some Debug::log calls or using a debugger to verify that 1) the hook is actually getting called and 2) the field is not named the same as an existing field or being added in a weird way, and 3) trying to establish when it drops off if that is indeed the case. If you send me the code of your extension I'd be happy to have a look as well.

**Comment by mediabeastnz** [comment]
In my yaml i'm extending CheckoutStep_Summary like this
```
CheckoutStep_Summary:
  extensions:
    - CheckoutStep_SummaryExtension
```

And then it seems like what ever I put inside 
`public function updateConfirmationForm($form) {}` 
it just doesn't get fired.

Is that the correct way to access that function?

**Comment by markguinn** [comment]
It does all look correct. Just for the sake of ruling it out - you did flush after this didn't you? So the extension config gets seen.

**Comment by markguinn** [comment]
Ok, so looking a little deeper, the problem is actually where your extension is getting attached. It shouldn't be to CheckoutStep_Summary because that appears to be an extension itself. I'm not sure where it SHOULD be, though. I think probably CheckoutPage_Controller but I don't know for certain.

**Comment by mediabeastnz** [comment]
Ok cool, i need this done so i'll play around a bit more and see IF I can get it firing without and core change. Otherwise it might require a small bit of core change with a PR or something?

**Comment by markguinn** [comment]
No, I think it will work if you just apply your extension to a different class. Notice that CheckoutStep_Summary is not applying extend on itself but on $this->owner. I think if you change your config to:

```
CheckoutPage_Controller:
  extensions:
    - CheckoutStep_SummaryExtension
```

You will be good to go.

**Comment by mediabeastnz** [comment]
Legend. works perfectly!
