### ISSUE TITLE
Address doesn't use customized required_fields in validate method.

### ISSUE THREAD

**Issue by bummzack** [burnbright/silverstripe-shop#369]
**Premise:** `Address::required_fields` should be customizable via config files (or in code by updating the config value).

This seems to be nicely implemented in `getRequiredFields`, but the `validate` method doesn't use these required fields, it reads directly from the static variable, which doesn't allow customization.

**Proposed fix:** Use `getRequiredFields` in the `validate` method as well.

Can create a PR for this if wanted.

**Comment by markguinn** [comment]
That sounds like a holdover from SS2.4. Good idea. If you've got time to create that PR that would be helpful. Thanks.

**Comment by bummzack** [comment]
I just noticed that this has been changed in the `develop` branch (I was looking at the 1.1.0 version). The `validate` method now uses `$this->config()->required_fields`.

I think it would still be better to use `getRequiredFields` instead, since it handles overrides and extensions as well.

**Comment by markguinn** [comment]
I agree

**Comment by bummzack** [comment]
Created a PR for this. #370

**Comment by markguinn** [comment]
Solved in #370
