### ISSUE TITLE
products need a base price to appear in their category

### ISSUE THREAD

**Issue by bbowden** [burnbright/silverstripe-shop#392]
I am loading products that have a number of variations. If I create a new product page without entering a price, the product does not appear on the shop category page. Adding a price and it appears.
This is OK if there are no variations, you can just add a price. If you add variations first without bothering about the base price, you can't add it later without deleting all the variations (and associated images) and starting again.

**Comment by markguinn** [comment]
I think there is a configure setting on product category to turn that off. Could be wrong though.

**Comment by bbowden** [comment]
You are correct. 
ProductCategory:
  must_have_price: true
is part of the example_config.yml. I think the default value is also 'true'

Now I'm looking at the BBEdit search results for 'config()->' and wondering if I should spend the time to convert that to a clean list of all possible configure settings. It won't give the possible values but if I kept the line references for each one . . .
Or maybe I should concentrate on getting this site sorted first.

**Comment by markguinn** [comment]
Glad to hear it! We're looking to improve the documentation so any contribution would be welcome. :)
