### ISSUE TITLE
ShopMigrationTask problem

### ISSUE THREAD

**Issue by ctx2002** [burnbright/silverstripe-shop#419]
My version is Silverstrip 3.2. 
used following command to install Shop module:

composer require burnbright/silverstripe-shop "*"

Now, run 
./framework/sake dev/tasks/ShopMigrationTask

I have got following error message:

>ERROR [User Error]: Uncaught SS_DatabaseException: Couldn't run query:

UPDATE "Product" SET "BasePrice" = "Price";

Unknown column 'Price' in 'field list'
IN GET /dev/tasks/ShopMigrationTask

**Comment by markguinn** [comment]
I believe those docs are outdated. That task isn't needed in a fresh install.
