### ISSUE TITLE
Inventory / Stock Tracking

### ISSUE THREAD

**Issue by jedateach** [burnbright/silverstripe-shop#53]
Inventory / stock handling could be incorporated into the officially supported modules.

Here's a few known existing solutions:

https://github.com/milkyway-multimedia/ss-shop-inventory
https://github.com/sunnysideup/silverstripe-ecommerce_stockcontrol
https://github.com/i-lateral/silverstripe-commerce-stockkeeping

**Comment by jedateach** [comment]
Note: https://github.com/milkyway-multimedia/ss-shop-inventory

**Comment by jedateach** [comment]
https://github.com/i-lateral/silverstripe-commerce-stockkeeping
https://github.com/sunnysideup/silverstripe-ecommerce_stockcontrol

**Comment by wilr** [comment]
We've now got that with the shop_stock module
